trigger: 
- none

pool:
  prakharself

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'


  - task: TerraformTask@5
    displayName: terraform init  
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
      backendServiceArm: 'xtrahunt'
      backendAzureRmResourceGroupName: 'rgtodo1'
      backendAzureRmStorageAccountName: 'cerrebal0708'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'dev.terraform.tfstate'

  - task: TerraformTask@5
    displayName: terraform validate
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'


  - task: TerraformTask@5
    displayName: terraform plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
      environmentServiceNameAzureRM: 'xtrahunt'


  

  
  

